import type { Metadata } from "next";
import { SITE_URL, getPublicSiteUrl, siteConfig } from "@/lib/site-config";

export { getSiteDomain } from "./seo-domain";

/** Raster OG/share image generated by src/app/opengraph-image.tsx */
export const DEFAULT_OG_IMAGE = "/opengraph-image";

export function trimTitle(text: string, max = 60): string {
  const normalized = text.replace(/\s+/g, " ").trim();
  if (normalized.length <= max) return normalized;
  return `${normalized.slice(0, max - 3).trimEnd()}...`;
}

export function trimDescription(text: string, max = 155): string {
  const normalized = text.replace(/\s+/g, " ").trim();
  if (normalized.length <= max) return normalized;
  return `${normalized.slice(0, max - 3).trimEnd()}...`;
}

export function absoluteUrl(path = "/"): string {
  const base = getPublicSiteUrl();
  if (!path || path === "/") return base;
  const p = path.startsWith("/") ? path : `/${path}`;
  return `${base}${p}`;
}

type PageMetadataInput = {
  title: string;
  description: string;
  path: string;
  noIndex?: boolean;
};

/** Per-page metadata with matching canonical + og:url and raster og:image. */
export function createPageMetadata({
  title,
  description,
  path,
  noIndex = false,
}: PageMetadataInput): Metadata {
  const url = absoluteUrl(path);
  const metaTitle = trimTitle(title);
  const metaDescription = trimDescription(description);
  const ogImage = absoluteUrl(DEFAULT_OG_IMAGE);

  return {
    title: { absolute: metaTitle },
    description: metaDescription,
    metadataBase: new URL(getPublicSiteUrl()),
    alternates: { canonical: url },
    openGraph: {
      title: metaTitle,
      description: metaDescription,
      url,
      siteName: siteConfig.name,
      type: "website",
      locale: "en_GB",
      images: [{ url: ogImage, alt: siteConfig.name, width: 1200, height: 630 }],
    },
    twitter: {
      card: "summary_large_image",
      title: metaTitle,
      description: metaDescription,
      images: [ogImage],
    },
    robots: noIndex
      ? { index: false, follow: false }
      : { index: true, follow: true },
  };
}

export { SITE_URL };
